spring:
  profiles:
    active: ${restaurantsServiceAppProfile}
  application:
    name: restaurants-service
  data:
    mongodb:
      uri: ${restaurantsServiceAppMongoURI}
      uuid-representation: standard
    database: ${restaurantsServiceMongoDbName}
redis:
  host: ${redisHost}
  port: ${redisPort}
  database: ${redisDatabase}
server:
  servlet:
    context-path: /restaurants_service

